//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesLedger.Transactions
{
    public partial class List
    {
        protected global::System.Web.UI.WebControls.Panel pnlList;
        protected global::System.Web.UI.WebControls.GridView gvTransactions;
        protected global::System.Web.UI.WebControls.Panel pnlDetail;
        protected global::System.Web.UI.WebControls.Literal litTxId;
        protected global::System.Web.UI.WebControls.Button btnBackToList;
        protected global::System.Web.UI.WebControls.GridView gvLines;
    }
}
