//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesLedger
{


    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.Literal litOpenOrders;
        protected global::System.Web.UI.WebControls.Literal litUnpaidInvoices;
        protected global::System.Web.UI.WebControls.Literal litPayments;
        protected global::System.Web.UI.WebControls.Literal litGLTx;
    }
}
