//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesLedger.Invoices
{
    public partial class Create
    {
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlSelectOrder;
        protected global::System.Web.UI.WebControls.DropDownList ddlSalesOrder;
        protected global::System.Web.UI.WebControls.Button btnPreview;
        protected global::System.Web.UI.WebControls.Panel pnlPreview;
        protected global::System.Web.UI.WebControls.Literal litSoId;
        protected global::System.Web.UI.WebControls.Literal litCustomer;
        protected global::System.Web.UI.WebControls.Literal litDate;
        protected global::System.Web.UI.WebControls.Repeater rptLines;
        protected global::System.Web.UI.WebControls.Literal litNetTotal;
        protected global::System.Web.UI.WebControls.Literal litTaxTotal;
        protected global::System.Web.UI.WebControls.Literal litGrossTotal;
        protected global::System.Web.UI.WebControls.HiddenField hfSalesOrderId;
        protected global::System.Web.UI.WebControls.Button btnConfirm;
        protected global::System.Web.UI.WebControls.Button btnBack;
    }
}
