//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesLedger.Inventory
{
    public partial class List
    {
        protected global::System.Web.UI.WebControls.GridView gvItems;
    }
}
