//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesLedger.SalesOrders
{
    public partial class Create
    {
        protected global::System.Web.UI.WebControls.ValidationSummary valSummary;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.DropDownList ddlCustomer;
        protected global::System.Web.UI.WebControls.TextBox txtDate;
        protected global::System.Web.UI.WebControls.Button btnAddLine;
        protected global::System.Web.UI.WebControls.Repeater rptLines;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
    }
}
